title:
  de: MRS Mind Research Systems GmbH
  en: MRS Mind Research Systems GmbH
description: 
  de:  Zürich 3D - Simulation & Gamification
  en:  Zürich 3D - Simulation & Gamification  
index:
  de: 
  en: en.html
theme: jekyll-theme-cayman
